### ISSUE TITLE
binding.gyp is not found

### ISSUE THREAD

**Issue by Sieabah** [toyobayashi/wasm-sjlj#3]
I'm not sure how or where I somehow pulled this dep in. Not for a lack of trying, this shows up as a direct dependency of my project but isn't in my package.json. `npm ls` doesn't show this anywhere either. I don't even know if this is the right repo for the npm module that is being used. I believe it is, but if this is just a micro module and emscripten is the primary repo where the published module lives then you can close this issue. This probably has something to do with wasm-bindgen, but I can't get this to install on any operating system. 

I only got it to install if I manage to install python 2.7 on windows and run that through miniconda. I don't think in 2024 a wasm-bindgen dep should be requiring something that was EoL 13 years ago. Is there a way to get this to install on mac, windows, or linux without having to compile with gyp?  

```
npm error gyp: binding.gyp not found (cwd: /Users/usera/.nvm/versions/node/v20.15.0/lib/node_modules/wasm-sjlj) while trying to load binding.gyp
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/Users/usera/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:297:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Darwin 23.6.0
npm error gyp ERR! command "/Users/usera/.nvm/versions/node/v20.15.0/bin/node" "/Users/usera/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /Users/usera/.nvm/versions/node/v20.15.0/lib/node_modules/wasm-sjlj
```

Is there a particular version of node & os I need to use or be on in order for this package to be installable? There is literally _zero_ documentation on anything about what this package requires.

I tried this on node 20 & 22

--

After going through a ton of verbose logging from npm this is a downsteam dependency from [canvas](https://www.npmjs.com/package/canvas). I've made sure all the deps from that are installed, but I think my problem is with that package and not this. However, this package _is_ impossible to install on MacOS, and there is no documentation so I'm not sure what can be done.

**Comment by toyobayashi** [comment]
Please try 1.0.6, feel free to reopen if it still error

**Comment by Sieabah** [comment]
Hi, thanks for a quick turn around here. Yes the problem with this package is resolved. There are other issues with the canvas package, but I think I'm just going to not use node-canvas and look for alternatives (@napi-rs/canvas). That package has been nothing but trouble to deal with.
